### ISSUE TITLE
403 Client Error: client.py:485

### ISSUE THREAD

**Issue by pgajeelh** [xob0t/google_photos_mobile_client#22]
I am having issues uploading via CLI due to the following error:

```
21:55:37 ERROR    Error uploading file (FILEPATH): 403 Client Error: client.py:485
                  Forbidden for url: https://android.googleapis.com/auth
```

I have tried 3 different auth_data but I am getting the same error. I think I may have been blocked by G0ogle as I attempted to do a hundred at a time the first time I stumbled upon this tool. Any help is greatly appreciated.

**Comment by AppStudioLB** [comment]
Have you tried obtaining auth_data using a rooted Android phone with ReVanced Google Photos?

**Comment by pgajeelh** [comment]
The first auth_data was from revanced with my rooted Android. Second and
third was from the official Google photos app. Should I try a different one
again with revanced gphotos?

**Comment by AppStudioLB** [comment]
Well, if auth_data has wrong format it can be happen. Did you use HTTP Toolkit for capture it?

**Comment by pgajeelh** [comment]
Yes. I used http toolkit and copied the body in text format. Let me try
again.

**Comment by AppStudioLB** [comment]
In my case, I used Android Studio Emulator to obtain auth_data. It was more convenient and easier.

**Comment by pgajeelh** [comment]
I tried doing this via bluestacks with root, revanced gphotos, and http toolkit. Still getting the same error. Not sure if I'm IP banned, but my uploads are going through just fine using the normal revanced gphotos app.

**Comment by lvandross-test** [comment]
Just tried to set this up and getting the same error. Testing with a single file to try and get this working. 

Set up a Pixel 9 in Android Studio, enabled root with rootAVD (not sure if this is needed), installed HTTP Toolkit with homebrew (on a Mac) and listened for the auth using the command in the Readme. Grabbed the auth_data and tried both in the terminal and as an env variable but same error. I did notice in the Readme that the command for the cli is incorrect in that it has the flag set to auth-data and not auth_data as it should be but most likely just a typo and not something that cascades down to the auth in an of itself. 

Any help here is greatly appreciated.

**Comment by xob0t** [comment]
@lvandross-test 
Since version 0.6.0 the cli arg to pass auth_data is `--auth-data`. Kebab case, as it should have been from the start.

Anyway, if you're getting 403 error that means it was passed correctly.
As to why this can happen, I cannot say.
I've set up multiple accounts, intercepting real devices and emulators, official play services and microg, and did not encounter this issue.
I can only suggest trying another device/emulator or revanced with microg.

**Comment by crocsnosockz** [comment]
> In my case, I used Android Studio Emulator to obtain auth_data. It was more convenient and easier.

What android version and photos version did you use. I was only able to intercept auth_data for https://www.googleapis.com/auth/mobileapps.native or auth/drive and many others but not photos.native itself.

**Comment by crocsnosockz** [comment]
@pgajeelh I actually managed to fix similar issue by using auth data from from this filter instead `contains(www.googleapis.com%2Fauth%2Fplus.photos.readwrite)` because I couldn't find any requests with `contains(https://www.googleapis.com/auth/photos.native)`  , there should only be one request.

Tested on: Android Studio emulator - Android 11 (Google API image), stock google photos app.

**Comment by xob0t** [comment]
I've updated the readme with a new way to get auth data from logcat.

**Comment by xob0t** [comment]
@pgajeelh 
Are your running it as CLI or a library?
Any trailing whitespaces in your auth_data string? - just noticed that could be one of the causes. Will fix in later versions.
Have you tried other google accounts? I doubt the issue is tied to the account but lets make sure.

**Comment by pgajeelh** [comment]
- running via CLI
- already tried another Google account using the new method
- ensured there are no trailing whitespaces in my auth_data

**Comment by pgajeelh** [comment]
Do you think this is Google’s way of blocking this method? This has never
worked for me so I stopped trying.

**Comment by tautomer** [comment]
I also encountered the same problem. I have a rooted Pixel XL so I used the HTTP Toolkit way to obtain the authtication string. I tried a different account on the same device. Still the same.

Edit: The Revanced way works. It's the token.

**Comment by Dindro** [comment]
> I also encountered the same problem. I have a rooted Pixel XL so I used the HTTP Toolkit way to obtain the authtication string. I tried a different account on the same device. Still the same.
> 
> Edit: The Revanced way works. It's the token.

I saw your message. I installed GmsCore and Revanced GP on my rooted phone. I received a token via ADB. It worked! Thanks!
